name: flutter_labs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  camera: ^0.11.0
  google_mlkit_face_detection: ^0.11.0
  dio: ^5.9.1
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/images/

flutter_native_splash:
  color: "#121212"
  image: assets/images/logo.jpeg
  android_12:
    color: "#121212"
    image: assets/images/logo.jpeg

flutter_launcher_icons:
  android: true
  image_path: assets/images/logo.jpeg
